server:
  port: 8081

output:
  ansi:
    enabled: DETECT
logging:
  file: spring_boot.log
message: welcome
swagger:
  enabled: true  
debug: false
mybatis:
  mapper-locations: classpath:mapper/*.xml                                 

spring:
    datasource:
        url: jdbc:mysql://192.168.1.22:3306/springboot_demo?characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver



